# Generated by Django 5.0 on 2024-12-11 13:22

import Accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_is_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='address_proof',
            field=models.ImageField(blank=True, null=True, upload_to='s-profile-images/', validators=[Accounts.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='librarian',
            name='adhar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='librarian',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
