# Generated by Django 5.0 on 2024-12-12 06:55

import Accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_librarian_address_proof_librarian_adhar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officestaff',
            name='address_proof',
            field=models.ImageField(blank=True, null=True, upload_to='s-profile-images/', validators=[Accounts.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='adhar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
