# Generated by Django 5.0 on 2024-12-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_student_details_libraryhystory_feeremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeremark',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_studentid', to='Accounts.student_details'),
        ),
    ]
