# Generated by Django 5.0 on 2024-12-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_feeremark_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeremark',
            name='fee_type',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('razorpay', 'razorpay'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('cash', 'Cash')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
